### ISSUE TITLE
running error with bsextractor

### ISSUE THREAD

**Issue by kkim-everest** [hippo-yf/bsgenova#4]
Hi Yance Feng,

I'm trying SNP calling from the targeted BS-seq dataset using bsgenova. But bsextractor.py gave me the error below. 
It already created 47M lines of the output (~chr12) then suddenly stopped with the error below. I'm using BAM file from Bismark, and it's deduplicated.

> Traceback (most recent call last):
  File "/Volumes/G-DRIVE-SSD/EverestDetection/working/pipeline_dev/Methylation-Seq/bsgenova/bsgenova-main/bsextractor.py", line 346, in <module>
    methylExtractor(params)
  File "/Volumes/G-DRIVE-SSD/EverestDetection/working/pipeline_dev/Methylation-Seq/bsgenova/bsgenova-main/bsextractor.py", line 251, in methylExtractor
    CG_context = '--' if 'N' in bases_con else CG_CONTEXT_FORWARD_HASH[bases_con]
                                               ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'CAM'

Best,

**Comment by hippo-yf** [comment]
It is caused by the unexpected letter M. The bug has been fixed now.

**Comment by kkim-everest** [comment]
Awesome! Thank you for the quick response!!
It's working now
